graph TD
    source["ソース\naisecure/control/documents.py"]
    n-threading-c3015a["threading\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-threading-c3015a
    n-signal-36ab4a["signal\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-signal-36ab4a
    n-secrets-fe8655["secrets\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-secrets-fe8655
