graph TD
    source["ソース\naisecure/control/documents.py"]
    n-future-05a733["__future__\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-future-05a733
    n-base64-8095e1["base64\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-base64-8095e1
    n-dataclasses-cebf61["dataclasses\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-dataclasses-cebf61
    n-io-5a2582["io\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-io-5a2582
    n-os-999a34["os\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-os-999a34
    n-pathlib-4471f7["pathlib\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-pathlib-4471f7
    n-re-c387c9["re\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-re-c387c9
    n-subprocess-d2d1e1["subprocess\n外部・別名・未解決"]
    source -->|"Python AST: import／export"| n-subprocess-d2d1e1
