graph TD
    n-examples-control-4381af["control\nexamples/control"]
    n-examples-logs-fcf360["logs\nexamples/logs"]
    n-examples-make-example-logs-py-e8f804["make-example-logs.py\nexamples/make-example-logs.py"]
    n-examples-synthetic-snapshot-json-b798ef["synthetic-snapshot.json\nexamples/synthetic-snapshot.json"]
