graph TD
    n-aisecure-02fec8["aisecure\naisecure"]
    n-browser-ef9836["browser\nbrowser"]
    n-deploy-b0d51b["deploy\ndeploy"]
    n-deployment-7233fb["deployment\ndeployment"]
    n-docs-71ab8b["docs\ndocs"]
    n-examples-99345c["examples\nexamples"]
    n-pyproject-toml-5d07e7["pyproject.toml\npyproject.toml"]
    n-scripts-16728d["scripts\nscripts"]
