graph TD
    n-docs-evaluation-281bf8["evaluation\ndocs/evaluation"]
    n-docs-evidence-3d7bf7["evidence\ndocs/evidence"]
    n-docs-media-17908a["media\ndocs/media"]
    n-docs-operations-8f703d["operations\ndocs/operations"]
    n-docs-quality-8a58ae["quality\ndocs/quality"]
    n-docs-screenshots-43be7c["screenshots\ndocs/screenshots"]
    n-docs-security-d04e3e["security\ndocs/security"]
    n-docs-site-5e78da["site\ndocs/site"]
