graph TD
    n-aisecure-connectors-a9084e["connectors\naisecure/connectors"]
    n-aisecure-control-673ca0["control\naisecure/control"]
    n-aisecure-legacy-web-012b00["legacy_web\naisecure/legacy_web"]
    n-aisecure-providers-b938e8["providers\naisecure/providers"]
    n-aisecure-workbench-web-dff821["workbench_web\naisecure/workbench_web"]
    n-aisecure-init-py-0a6f15["__init__.py\naisecure/__init__.py"]
    n-aisecure-main-py-2643e0["__main__.py\naisecure/__main__.py"]
    n-aisecure-approvals-py-f54309["approvals.py\naisecure/approvals.py"]
