'use strict';
const $=id=>document.getElementById(id);
let token=new URLSearchParams(location.hash.slice(1)).get('token')||'';
history.replaceState(null,'',location.pathname);
let requestId;const newId=()=>{requestId=crypto.randomUUID().replaceAll('-','');$('request-id').textContent=requestId;$('label').value='';$('consent').checked=false;};newId();
const text=(tag,value)=>{const el=document.createElement(tag);el.textContent=value;return el;};
const names={allow:'検査通過',block:'拒否',review:'保留',no_findings:'検出なし（許可ではありません）',not_connected:'未接続'};
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'Authorization':'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw Error((await response.json()).error||'結果未確認です。');return response;}
async function files(){const selected=[...$('files').files];if(!selected.length||selected.length>4||selected.reduce((n,f)=>n+f.size,0)>16*1024*1024)throw Error('1〜4件、合計16MiBまでの資料を選択してください。');return Promise.all(selected.map(file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(Error('資料を読めません。'));r.onload=()=>resolve({format:file.name.split('.').pop().toLowerCase(),base64:r.result.split(',')[1]});r.readAsDataURL(file);})));}
async function busy(fn){document.querySelectorAll('button').forEach(b=>b.disabled=true);$('status').textContent='処理しています。';try{await fn();$('status').textContent='確認結果を更新しました。';}catch(e){$('status').textContent=e.message;}finally{document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function renderResult(obj){$('result').replaceChildren();const box=text('article','');box.append(text('h3',names[obj.decision]||'確認結果'));if(obj.execution_state)box.append(text('p','実行状態：'+obj.execution_state));for(const [i,d]of (obj.documents||[]).entries()){box.append(text('h3',`資料 ${i+1} · ${d.format}`));box.append(text('p',`検査範囲：${d.coverage} / ${d.units}単位`));box.append(text('p',d.findings.map(f=>`${f.rule}：${f.count}件`).join('、')||'対応する文字範囲での検出はありません。'));}if(obj.rules?.length)box.append(text('p','判定根拠：'+obj.rules.join('、')));if(obj.output)box.append(text('pre',obj.output));if(obj.text!==undefined){box.append(text('p','レイアウトや計算式を保持しないテキスト案です。未検査の内容は含まれず、再分類が必要です。'));box.append(text('pre',obj.text));}box.append(text('small','安全性の保証ではありません。検査範囲と未確認の内容を確認してください。'));$('result').append(box);}
async function operation(path){let label;try{label=$('label').value.trim()?JSON.parse($('label').value):undefined;}catch{throw Error('分類証明のJSONを確認してください。');}const payload={question:$('question').value,files:await files(),request_id:requestId,...(label?{label}:{}),consent:$('consent').checked};renderResult(await(await api(path,payload)).json());await refresh();}
$('check').onclick=()=>busy(()=>operation('/api/check'));$('send').onclick=()=>busy(()=>operation('/api/send'));
$('preview').onclick=()=>busy(async()=>renderResult(await(await api('/api/preview',{files:await files(),consent:true})).json()));
$('question').addEventListener('input',newId);$('files').addEventListener('change',newId);
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==b.dataset.tab;for(const n of document.querySelectorAll('[data-tab]')){n.removeAttribute('aria-current');}b.setAttribute('aria-current','page');};
async function refresh(){const state=await(await api('/api/state')).json();$('mode').textContent=state.mode==='demo'?'DEMO · 外部送信なし':state.delivery_enabled?'管理対象経路':'管理モード · 外部AI送信無効';$('demo').hidden=state.mode!=='demo';$('cases').replaceChildren();for(const c of state.analysis.cases){const card=text('article','');card.append(text('span',c.priority+' / '+c.rule),text('h3',c.observed),text('p','可能性：'+c.hypothesis),text('p','未確認：'+c.unknown.join(' ')),text('small','証跡 '+c.evidence_count+'件 / 自動操作なし'));$('cases').append(card);}if(!state.analysis.cases.length)$('cases').append(text('p','現在の入力では確認候補がありません。未収集の経路は分析できません。'));$('vpn-results').replaceChildren();if(!state.vpn)$('vpn-results').append(text('p','VPN台帳・設定の観測は未接続です。'));else{for(const f of state.vpn.posture.findings){const card=text('article','');card.append(text('h3',`${f.asset_id} · ${f.priority}`),text('p',f.status),text('p',f.reasons.join(' ')));$('vpn-results').append(card);}for(const f of state.vpn.controls)$('vpn-results').append(text('p',f.observed));}$('history').replaceChildren();for(const event of state.history){const card=text('article','');card.append(text('p',`${new Date(event.at*1000).toLocaleString()} · ${event.kind}`),text('p',`${names[event.decision]||event.decision} / ${event.execution_state}`),text('small',(event.rules||[]).join('、')));$('history').append(card);}}
$('demo').onclick=()=>busy(async()=>{await api('/api/demo',{});await refresh();});
$('export').onclick=()=>busy(async()=>{const response=await api('/api/audit');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='aisecure-audit.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
busy(refresh);
