graph TD
    n-tools-init-py-6ae81e["__init__.py\ntools/__init__.py"]
    n-tools-build-demo-video-py-169656["build_demo_video.py\ntools/build_demo_video.py"]
    n-tools-build-release-py-27d2ed["build_release.py\ntools/build_release.py"]
    n-tools-capture-py-502756["capture.py\ntools/capture.py"]
    n-tools-check-control-py-5dbe3c["check_control.py\ntools/check_control.py"]
    n-tools-check-control-package-py-33d03b["check_control_package.py\ntools/check_control_package.py"]
    n-tools-check-product-presentation-py-5c112f["check_product_presentation.py\ntools/check_product_presentation.py"]
    n-tools-check-workbench-py-471bad["check_workbench.py\ntools/check_workbench.py"]
