(()=>{'use strict';
const $=s=>document.querySelector(s),states={not_executed:'検査のみ・未送信',prevented_in_gateway:'この送信経路で拒否・送信処理は未実行',dispatch_pending:'処理中または結果未確認・再送しません',delivery_unknown:'送信結果は未確認・自動再送しません',demo_received:'デモ受信器で受信を確認・外部AIへは未送信',provider_completed:'AIプロバイダーの完了応答を確認'};
let token=new URLSearchParams(location.hash.slice(1)).get('token')||'',rid=crypto.randomUUID().replaceAll('-',''),mode='unknown',busy=false,checked=false;
history.replaceState(null,'',location.pathname);$('#request-id').textContent=rid;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function reset(newid=true){if(newid)rid=crypto.randomUUID().replaceAll('-','');$('#request-id').textContent=rid;checked=false;$('#send').disabled=true;$('#consent').checked=false;$('#result').replaceChildren(el('p','内容が変わりました。もう一度検査してください。','empty'))}
function payload(){const s=$('#sample').value;return {request_id:rid,...(mode==='demo'&&s?{sample:s}:{text:$('#text').value,...($('#label').value.trim()?{label:JSON.parse($('#label').value)}:{})})}}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const obj=await r.json();if(!r.ok)throw Error(obj.error||'接続できませんでした。');return obj}
function result(r){const box=$('#result');box.replaceChildren(el('span',({allow:'検査通過',block:'拒否',review:'保留'})[r.decision]||'結果','badge '+r.decision),el('h3',r.decision==='allow'?'送信前の確認ができました。':'このままでは送信しません。'));const list=el('ul');for(const reason of r.reasons||[])list.append(el('li',reason));box.append(list,el('p',states[r.execution_state]||r.execution_state,'state'));for(const next of r.next_steps||[])box.append(el('p',next));if(r.replayed)box.append(el('p','同じ操作の記録を返しています。再送していません。','fine'));if(r.output)box.append(el('div',r.output,'output'));box.append(el('p','根拠: '+(r.rule_ids.join(', ')||'登録ポリシーとの一致'),'fine'));checked=r.decision==='allow';$('#send').disabled=!checked||busy}
async function refresh(){try{const s=await api('/api/state');mode=s.mode;$('#mode').textContent=mode==='demo'?'デモモード — 合成例で検査と送信経路を試せます。外部AIへ送信しません。':'実接続モード — OpenAIへ本文を送信します。API料金が発生します。端末全体の保護ではありません。';$('#mode').classList.toggle('live',mode!=='demo');$('#sample-controls').hidden=mode!=='demo';$('#text').disabled=mode==='demo'&&Boolean($('#sample').value);$('#auth').open=false;const grid=el('div',undefined,'scope-grid');for(const [title,desc] of [['管理対象','この画面を通るテキスト送信'],['監視していない範囲','PC全体・USB・VPN機器'],['外部DLP収集',s.coverage.collector_configured?(s.coverage.collector_stale?'記録なし・停止または遅延を確認':'最近の記録あり（制御の有効性は未確認）'):'未接続']]){const d=el('div');d.append(el('b',title),el('p',desc));grid.append(d)}$('#coverage').replaceChildren(grid);const posture=$('#posture');posture.replaceChildren();for(const f of [...(s.posture.findings||[]),...(s.dlp_findings||[])]){posture.append(el('p',f.summary||((f.asset_id||'資産')+' / '+f.status+' / '+(f.reasons||[]).join(' '))))}if(!posture.children.length)posture.append(el('p',s.posture.scope==='not_connected'?'資産台帳は未接続です。DLPも、観測データがなければ安全とは判断しません。':s.posture.scope==='collection_failed_or_invalid'?'台帳を取得・検証できません。入力と鮮度を確認してください。':'入力された範囲に確認事項はありません。全体の安全性を示すものではありません。'));$('#history').replaceChildren();for(const r of s.history){const n=el('div',undefined,'record'),d=el('div');d.append(el('b',r.kind==='dlp_observation'?'外部DLPの観測記録':states[r.execution_state]||'監査記録'),el('p',new Date(r.at*1000).toLocaleString()+' / #'+r.seq));n.append(d);if(r.reasons){const b=el('button','理由を説明','secondary');b.type='button';b.onclick=async()=>{b.disabled=true;try{const x=await api('/api/explain',{seq:r.seq});$('#explanation').textContent=x.summary+'\n\n'+x.checks.join('\n')+'\n\n'+x.note}catch(e){$('#explanation').textContent=e.message}finally{b.disabled=false}};n.append(b)}$('#history').append(n)}if(!s.history.length)$('#history').append(el('p','まだ記録はありません。サンプルを選んで検査してください。'));}catch(e){$('#mode').textContent=e.message;$('#auth').open=true}}
async function run(send){if(busy)return;busy=true;$('#check').disabled=true;$('#send').disabled=true;try{const p=payload();if(send&&!$('#consent').checked)throw Error('送信先と内容の確認欄をチェックしてください。');const r=await api(send?'/api/send':'/api/check',{...p,...(send?{consent:true}:{})});result(r);await refresh()}catch(e){$('#result').replaceChildren(el('p',e.message,'state'));checked=false}finally{busy=false;$('#check').disabled=false;$('#send').disabled=!checked}}
$('#check').onclick=()=>run(false);$('#send').onclick=()=>run(true);$('#refresh').onclick=refresh;$('#connect').onclick=()=>{token=$('#token').value.trim();$('#token').value='';refresh()};$('#sample').onchange=()=>{reset();$('#label').value='';$('#text').disabled=Boolean($('#sample').value)};$('#text').oninput=()=>{reset();$('#label').value=''};$('#label').oninput=()=>reset(false);refresh();
})();
